#!/usr/bin/python3
import sys, socket
import traceback

if __name__ == '__main__':
    args = sys.argv[1:]
    try: 
        udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        udp.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        udp_addr = (args[0], int(args[1]))
        sent_data = None
        while sent_data != 'EXIT': 
            sent_data = input()
            udp.sendto(sent_data.encode(), udp_addr)
            print(f"{sent_data} DATA BROADCASTED")
    except socket.error as e:
        print(f"ERROR OCCURRED: {str(e)}")
        traceback.print_exception(*sys.exc_info())
        exit(-1)
